# -*- coding: utf-8 -*-
"""Mini_API_Call_Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1W44U0wVK-OxKAjkezPGcEgI6bx1t64
"""

# =============================================
# 📒 API_Fundamentals_Demo.ipynb
# Day 10 – Mini API Demo
# =============================================

# =============================================
# 1️⃣ Introduction (Markdown cell)
# =============================================
"""
# 🧪 Mini API Demo – JSONPlaceholder

✨ This notebook demonstrates how to **call a public API**, save results as JSON,
and automatically generate a Markdown report.

We use JSONPlaceholder for demo purposes (a free REST API), making this project
perfect for learning **API workflows in Python**.
"""

# =============================================
# 2️⃣ Import Required Libraries
# =============================================
import requests
import json

# =============================================
# 3️⃣ Call the API
# =============================================
API_URL = "https://jsonplaceholder.typicode.com/posts/1"

response = requests.get(API_URL)
data = response.json()

print("✅ API response fetched successfully:")
print(data)

# =============================================
# 4️⃣ Save Results as JSON
# =============================================
with open("results.json", "w") as f:
    json.dump(data, f, indent=4)

print("\n💾 Saved results to results.json")

# =============================================
# 5️⃣ Generate Markdown Report
# =============================================
markdown_text = f"""
# 🧪 Mini API Demo – JSONPlaceholder

| **Field** | **Value** |
|-----------|-----------|
| User ID   | {data['userId']} |
| Post ID   | {data['id']} |
| Title     | {data['title']} |
| Body      | {data['body'][:50]}... |

✅ Results also saved in `results.json`
"""

with open("API_Demo_Report.md", "w") as f:
    f.write(markdown_text)

print("\n📄 Markdown report created: API_Demo_Report.md")
print("\n✨ Demo complete! Open 'API_Demo_Report.md' to view your Markdown summary.")
print("\n---\nMarkdown Preview:\n")
print(markdown_text)

# =============================================
# 6️⃣ Optional Notes (Markdown cell)
# =============================================
"""
## 💡 Notes

- The API used is JSONPlaceholder (free demo API)
- Markdown formatting truncates long text for readability
- Ideal for practicing **API calls, JSON handling, and Markdown generation**

## 📢 Optional Sharing
Share on LinkedIn or GitHub:
*"Built a mini API demo in Python – fetched live data, saved JSON, and generated a Markdown report automatically! 🚀 #Python #APIs #LearningInPublic"*
"""